name: Test Actions

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'
          update-conda: true
          conda-channels: anaconda, conda-forge
      - uses: actions/setup-java@v3
        with:
         distribution: 'temurin' # See 'Supported distributions' for available options
         java-version: '8'

         
      - run: conda --version
      
      - name: create Anaconda environment
        run: |
     
         $CONDA/bin/conda env create --file environment_cpu.yml 
         $CONDA/bin/activate hybridintelligence
         
      - name: Install requirements
        run: |
         
         pip install -r requirements.txt
         
      - name: Install dataset
        run: |
          pip install minerl
          python downloadBasaltDataset.py
         
      - name: data processing
        run: |
        
         python dataProcessing.py
         
      - name: label data
        run: |
         
         pip install scikit-multilearn
         python compileLabels.py


      - name: Training
        run: |
          pip install crowdai_api
          python train.py
          
      - name: Test
        run: |
          python test.py
