name: Test Actions

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.7'
          update-conda: true
          conda-channels: anaconda, conda-forge
          
      - name: Install openjdk
        run: 
         sudo add-apt-repository ppa:openjdk-r/ppa
         sudo apt-get update
         sudo apt-get install openjdk-8-jdk
         
      - run: conda --version
      
      - name: create Anaconda environment
        run: |
     
         $CONDA/bin/conda env create --file environment_cpu.yml 
         $CONDA/bin/activate hybridintelligence
         
      - name: Install requirements
        run: |
         pip install --upgrade minerl
         pip install -r requirements.txt
         
      - name: Install dataset
        run: |
          
          python downloadBasaltDataset.py
         
      - name: data processing
        run: |
        
         pip install opencv-python numpy
         python dataProcessing.py
         
      - name: label data
        run: |
         
         pip install scikit-multilearn
         python compileLabels.py

      - name: Dataset
        run: |
          
          
          

      - name: Training
        run: |
          python train.py
          
      - name: Test
        run: |
          python test.py
